// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ReaderRequest.proto
// Protobuf C++ Version: 5.29.2

#include "ReaderRequest.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ReaderRequest {

inline constexpr ReaderRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{},
        cmd_{static_cast< ::ReaderRequest::Command >(0)},
        msgcnt_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReaderRequest::ReaderRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReaderRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReaderRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReaderRequestDefaultTypeInternal() {}
  union {
    ReaderRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReaderRequestDefaultTypeInternal _ReaderRequest_default_instance_;
}  // namespace ReaderRequest
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ReaderRequest_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ReaderRequest_2eproto = nullptr;
const ::uint32_t
    TableStruct_ReaderRequest_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ReaderRequest::ReaderRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ReaderRequest::ReaderRequest, _impl_.cmd_),
        PROTOBUF_FIELD_OFFSET(::ReaderRequest::ReaderRequest, _impl_.msgcnt_),
        PROTOBUF_FIELD_OFFSET(::ReaderRequest::ReaderRequest, _impl_.result_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ReaderRequest::ReaderRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::ReaderRequest::_ReaderRequest_default_instance_._instance,
};
const char descriptor_table_protodef_ReaderRequest_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023ReaderRequest.proto\022\rReaderRequest\"T\n\r"
    "ReaderRequest\022#\n\003cmd\030\001 \001(\0162\026.ReaderReque"
    "st.Command\022\016\n\006msgCnt\030\002 \001(\005\022\016\n\006result\030\003 \003"
    "(\t*\362\002\n\007Command\022\013\n\007Cmd_Err\020\000\022\037\n\033Cmd_SCard"
    "_Establish_Context\020e\022\031\n\025Cmd_SCard_Reader"
    "_List\020f\022\032\n\026Cmd_SCard_Connect_Card\020g\022\035\n\031C"
    "md_SCard_Disconnect_Card\020h\022\026\n\022Cmd_SCard_"
    "Transmit\020i\022\023\n\016Cmd_MI_Get_UID\020\311\001\022\024\n\017Cmd_M"
    "I_Load_Key\020\312\001\022\032\n\025Cmd_MI_Authentication\020\313"
    "\001\022\026\n\021Cmd_Mi_Read_Block\020\314\001\022\027\n\022Cmd_Mi_Writ"
    "e_Block\020\315\001\022\025\n\020Cmd_Mi_Decrement\020\316\001\022\025\n\020Cmd"
    "_Mi_Increment\020\317\001\022\023\n\016Cmd_Mi_Restore\020\320\001\022\020\n"
    "\013Cmd_Mi_HALT\020\321\001b\006proto3"
};
static ::absl::once_flag descriptor_table_ReaderRequest_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ReaderRequest_2eproto = {
    false,
    false,
    503,
    descriptor_table_protodef_ReaderRequest_2eproto,
    "ReaderRequest.proto",
    &descriptor_table_ReaderRequest_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ReaderRequest_2eproto::offsets,
    file_level_enum_descriptors_ReaderRequest_2eproto,
    file_level_service_descriptors_ReaderRequest_2eproto,
};
namespace ReaderRequest {
const ::google::protobuf::EnumDescriptor* Command_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ReaderRequest_2eproto);
  return file_level_enum_descriptors_ReaderRequest_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Command_internal_data_[] = {
    65536u, 224u, 0u, 0u, 0u, 496u, 0u, 0u, 130816u, };
bool Command_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, Command_internal_data_);
}
// ===================================================================

class ReaderRequest::_Internal {
 public:
};

ReaderRequest::ReaderRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ReaderRequest.ReaderRequest)
}
inline PROTOBUF_NDEBUG_INLINE ReaderRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ReaderRequest::ReaderRequest& from_msg)
      : result_{visibility, arena, from.result_},
        _cached_size_{0} {}

ReaderRequest::ReaderRequest(
    ::google::protobuf::Arena* arena,
    const ReaderRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReaderRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, cmd_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, cmd_),
           offsetof(Impl_, msgcnt_) -
               offsetof(Impl_, cmd_) +
               sizeof(Impl_::msgcnt_));

  // @@protoc_insertion_point(copy_constructor:ReaderRequest.ReaderRequest)
}
inline PROTOBUF_NDEBUG_INLINE ReaderRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : result_{visibility, arena},
        _cached_size_{0} {}

inline void ReaderRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, cmd_),
           0,
           offsetof(Impl_, msgcnt_) -
               offsetof(Impl_, cmd_) +
               sizeof(Impl_::msgcnt_));
}
ReaderRequest::~ReaderRequest() {
  // @@protoc_insertion_point(destructor:ReaderRequest.ReaderRequest)
  SharedDtor(*this);
}
inline void ReaderRequest::SharedDtor(MessageLite& self) {
  ReaderRequest& this_ = static_cast<ReaderRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ReaderRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ReaderRequest(arena);
}
constexpr auto ReaderRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_.result_) +
          decltype(ReaderRequest::_impl_.result_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ReaderRequest), alignof(ReaderRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ReaderRequest::PlacementNew_,
                                 sizeof(ReaderRequest),
                                 alignof(ReaderRequest));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ReaderRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ReaderRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ReaderRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ReaderRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ReaderRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ReaderRequest>(), &ReaderRequest::ByteSizeLong,
            &ReaderRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_._cached_size_),
        false,
    },
    &ReaderRequest::kDescriptorMethods,
    &descriptor_table_ReaderRequest_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ReaderRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 42, 2> ReaderRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ReaderRequest::ReaderRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .ReaderRequest.Command cmd = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReaderRequest, _impl_.cmd_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_.cmd_)}},
    // int32 msgCnt = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReaderRequest, _impl_.msgcnt_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_.msgcnt_)}},
    // repeated string result = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .ReaderRequest.Command cmd = 1;
    {PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_.cmd_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 msgCnt = 2;
    {PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_.msgcnt_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated string result = 3;
    {PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\33\0\0\6\0\0\0\0"
    "ReaderRequest.ReaderRequest"
    "result"
  }},
};

PROTOBUF_NOINLINE void ReaderRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ReaderRequest.ReaderRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_.Clear();
  ::memset(&_impl_.cmd_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.msgcnt_) -
      reinterpret_cast<char*>(&_impl_.cmd_)) + sizeof(_impl_.msgcnt_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ReaderRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ReaderRequest& this_ = static_cast<const ReaderRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ReaderRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ReaderRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ReaderRequest.ReaderRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .ReaderRequest.Command cmd = 1;
          if (this_._internal_cmd() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_cmd(), target);
          }

          // int32 msgCnt = 2;
          if (this_._internal_msgcnt() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_msgcnt(), target);
          }

          // repeated string result = 3;
          for (int i = 0, n = this_._internal_result_size(); i < n; ++i) {
            const auto& s = this_._internal_result().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ReaderRequest.ReaderRequest.result");
            target = stream->WriteString(3, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ReaderRequest.ReaderRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ReaderRequest::ByteSizeLong(const MessageLite& base) {
          const ReaderRequest& this_ = static_cast<const ReaderRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ReaderRequest::ByteSizeLong() const {
          const ReaderRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ReaderRequest.ReaderRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string result = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_result().size());
              for (int i = 0, n = this_._internal_result().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_result().Get(i));
              }
            }
          }
           {
            // .ReaderRequest.Command cmd = 1;
            if (this_._internal_cmd() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_cmd());
            }
            // int32 msgCnt = 2;
            if (this_._internal_msgcnt() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_msgcnt());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ReaderRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReaderRequest*>(&to_msg);
  auto& from = static_cast<const ReaderRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ReaderRequest.ReaderRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_result()->MergeFrom(from._internal_result());
  if (from._internal_cmd() != 0) {
    _this->_impl_.cmd_ = from._impl_.cmd_;
  }
  if (from._internal_msgcnt() != 0) {
    _this->_impl_.msgcnt_ = from._impl_.msgcnt_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReaderRequest::CopyFrom(const ReaderRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReaderRequest.ReaderRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReaderRequest::InternalSwap(ReaderRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.result_.InternalSwap(&other->_impl_.result_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_.msgcnt_)
      + sizeof(ReaderRequest::_impl_.msgcnt_)
      - PROTOBUF_FIELD_OFFSET(ReaderRequest, _impl_.cmd_)>(
          reinterpret_cast<char*>(&_impl_.cmd_),
          reinterpret_cast<char*>(&other->_impl_.cmd_));
}

::google::protobuf::Metadata ReaderRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ReaderRequest
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ReaderRequest_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
